# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: $CONTAINER_REGISTRY/book_catalog:$VERSION
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://part5_v4ll_user:NfycylKYmM9CvpUn9QKkeSX7eXpXVnw0@dpg-crjnegdds78s73eccul0-a.oregon-postgres.render.com/part5_v4ll"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000