apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory_management:$VERSION
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "postgresql://test_qvyg_user:BxUvRQ6bGxUyn5isMjxdMivC239aNyjj@dpg-crv60atds78s73a91or0-a.oregon-postgres.render.com/test_qvyg"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000