name: Deploy book_catalog

on:
  # Trigger the workflow on push to the master branch or changes to book_catalog directory
  push: 
    branches:
      - master
    paths:
      - book_catalog/**

  # Allows the workflow to be triggered manually
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r book_catalog/requirements.txt  # Ensure your requirements are in this file
      
      # Run tests
      - name: Run tests
        run: |
          pytest -v -s book_catalog/tests/test_main.py  # Adjust the path to your test files as necessary

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures the deploy job runs after the test job

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      NAME: book_catalog
      DIRECTORY: book_catalog
      EMAIL_TO: ${{ secrets.EMAIL_TO }}  # Recipient email address
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}  # Sender email address
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}  # SMTP server
      SMTP_PORT: ${{ secrets.SMTP_PORT }}  # SMTP port
      SMTP_USER: ${{ secrets.SMTP_USER }}  # SMTP username
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  # SMTP password

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set executable permissions for all necessary scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x ./scripts/build-image.sh
          chmod +x ./scripts/push-image.sh
          chmod +x ./scripts/deploy.sh

      # Build the Docker image
      - name: Build Docker image
        run: ./scripts/build-image.sh

      # Push the Docker image to the container registry
      - name: Publish Docker image
        run: ./scripts/push-image.sh

      # Install Kubectl and configure it with the cluster
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Deploy the microservice to Kubernetes
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh

      # Notify via email on successful deployment
      - name: Notify via email of successful deployment
        if: success()  # Only notify if the job was successful
        run: |
          echo "Deployment of book_catalog succeeded!" | mail -s "Deployment Success: book_catalog" -a "From: $EMAIL_FROM" -S smtp="$SMTP_SERVER:$SMTP_PORT" -S smtp-auth=login -S smtp-auth-user="$SMTP_USER" -S smtp-auth-password="$SMTP_PASSWORD" "$EMAIL_TO"

      # Notify via email on failure
      - name: Notify via email of failure
        if: failure()  # Notify if the job failed
        run: |
          echo "Deployment of book_catalog failed!" | mail -s "Deployment Failure: book_catalog" -a "From: $EMAIL_FROM" -S smtp="$SMTP_SERVER:$SMTP_PORT" -S smtp-auth=login -S smtp-auth-user="$SMTP_USER" -S smtp-auth-password="$SMTP_PASSWORD" "$EMAIL_TO"
