# GitHub Actions workflow to deploy Terraform infrastructure.
name: Deploy Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - .scripts/terraform/**

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init
        working-directory: .scripts/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: .scripts/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .scripts/terraform
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
