# GitHub Actions workflow for deploying Terraform infrastructure.

name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-infrastructure.yaml

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Create Terraform Configuration
        run: |
          echo 'provider "azurerm" {' > main.tf
          echo '  features {}' >> main.tf
          echo '}' >> main.tf
          echo '' >> main.tf
          echo 'resource "azurerm_resource_group" "bmok1" {' >> main.tf
          echo '  name     = var.app_name' >> main.tf
          echo '  location = var.location' >> main.tf
          echo '}' >> main.tf
          echo '' >> main.tf
          echo 'resource "azurerm_kubernetes_cluster" "cluster" {' >> main.tf
          echo '  name                = var.app_name' >> main.tf
          echo '  location            = var.location' >> main.tf
          echo '  resource_group_name = azurerm_resource_group.bmok1.name' >> main.tf
          echo '  dns_prefix          = var.app_name' >> main.tf
          echo '  kubernetes_version  = var.kubernetes_version' >> main.tf
          echo '  default_node_pool {' >> main.tf
          echo '    name            = "default"' >> main.tf
          echo '    node_count      = 1' >> main.tf
          echo '    vm_size         = "Standard_D2s_v3"' >> main.tf
          echo '  }' >> main.tf
          echo '  identity {' >> main.tf
          echo '    type = "SystemAssigned"' >> main.tf
          echo '  }' >> main.tf
          echo '}' >> main.tf
          echo '' >> main.tf
          echo 'resource "azurerm_container_registry" "container_registry" {' >> main.tf
          echo '  name                = var.app_name' >> main.tf
          echo '  resource_group_name = azurerm_resource_group.bmok1.name' >> main.tf
          echo '  location            = var.location' >> main.tf
          echo '  admin_enabled       = true' >> main.tf
          echo '  sku                 = "Basic"' >> main.tf
          echo '}' >> main.tf

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
